trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  keyVaultName: 'your-keyvault-name'

jobs:
- job: ListKeyVaultItems
  steps:

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'your-service-connection-name'  # Azure Service Connection Name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Login to Azure
        az account set --subscription $(subscriptionId)
        
        # Get keys, secrets and certificates expiry dates from the Key Vault
        
        echo "Listing Keys in Key Vault: $(keyVaultName)"
        keys=$(az keyvault key list --vault-name $(keyVaultName) --query "[].{name: name, expiry: attributes.expires}" -o table)
        echo "$keys"

        echo "Listing Secrets in Key Vault: $(keyVaultName)"
        secrets=$(az keyvault secret list --vault-name $(keyVaultName) --query "[].{name: name, expiry: attributes.expires}" -o table)
        echo "$secrets"

        echo "Listing Certificates in Key Vault: $(keyVaultName)"
        certs=$(az keyvault certificate list --vault-name $(keyVaultName) --query "[].{name: name, expiry: attributes.expires}" -o table)
        echo "$certs"
    displayName: 'List Keys, Secrets, and Certificates Expiry Dates'
