---
- name: Monitor Keyword and Send Email
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check keyword in process list
      command: ps -ef | grep -I --color=never abc_def
      register: ps_output
      failed_when: false
      changed_when: false

    - name: Send email if keyword not found
      command: echo "Keyword not found" | sendmail user@example.com
      when: ps_output.stdout_lines | length == 0
