---
- name: Collect available packages and patch servers
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Collect available packages
      command: yum -q check-update | awk '{print $1}' |sed 's/\.x86_64$//' |sed 's/\.noarch$//' |sed 's/\.src$//' > /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-name.txt
      changed_when: false

    - name: Collect available package versions
      command: yum -q check-update | awk '{print $2} > /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-version.txt
      changed_when: false

    - name: Collect package names and package version details in installable format
      command: paste -d '-' /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-name.txt /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-version.txt | sed 's/\n/-/' > /dump/{{ inventory_hostname }}-only-packages-needs-install.txt
      changed_when: false

    - name:  Backup of package files generated to Install Same Package updates across all environments
      shell: |
        cp -rp /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-name.txt /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-name-$(date +"%y-%m-%d-%H-%m-%s").txt
        cp -rp /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-version.txt /dump/OS-Patch-Logs/{{ inventory_hostname }}-package-version-$(date +"%y-%m-%d-%H-%m-%s").txt
        cp -rp /dump/OS-Patch-Logs/{{ inventory_hostname }}-only-packages-needs-install.txt /dump/OS-Patch-Logs/{{ inventory_hostname }}-only-packages-needs-install-$(date +"%y-%m-%d-%H-%m-%s").txt

