- name: Audit user accounts on OCI Linux Compute instances
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get list of all user accounts
      shell: cat /etc/passwd | cut -d ":" -f 1
      register: user_list
      changed_when: false

    - name: Delete user account details file if it exists
      file:
        path: /tmp/user-account-list-details.txt
        state: absent
      delegate_to: localhost

    - name: Create user account details file if it doesn't exist
      file:
        path: /tmp/user-account-list-details.txt
        state: touch
      delegate_to: localhost
      when: not ansible_check_mode

    - name: Generate user account audit report
      shell: |
        printf "%-40s %-40s %-40s %-60s %-50s %-50s\n" "Username" "Shell" "Groups" "Last Login" "Password Expiry" "Last Password Change" > /tmp/user-account-list-details.txt
        for user in {{ user_list.stdout_lines | join(' ') }}; do
          groups=$(groups $user)
          shell=$(getent passwd $user | cut -d: -f7)
          last_login=$(lastlog -u $user |tail -n 1 | cut -c 44-)
          password_expiry=$(chage -l $user | grep 'Password expires' | cut -d ':' -f 2)
          last_password_change=$(chage -l $user | grep 'Last password change' | cut -d ':' -f 2)
          printf "%-40s %-40s %-40s %-60s %-50s %-50s\n" "$user" "$shell" "$groups" "$last_login" "$password_expiry" "$last_password_change" >> /tmp/user-account-list-details.txt
        done
      register: user_audit_report_output
      changed_when: false

    - name: Debug output of audit report
      debug:
        var: user_audit_report_output.stdout_lines

    - name: Debug output of file
      shell: cat /tmp/user-account-list-details.txt
      register: file_output
      changed_when: false

    - name: Format file contents with boxes
      shell: |
        echo "$(sed '1d' /tmp/user-account-list-details.txt | awk 'BEGIN {print "+----------------------------------------+----------------------------------------+----------------------------------------+------------------------------------------------------------+----------------------------------------------------+----------------------------------------------------+"} {print "| " $1 " | " $2 " | " $3 " | " $4 " | " $5 " | " $6 " |"} END {print "+----------------------------------------+----------------------------------------+----------------------------------------+------------------------------------------------------------+----------------------------------------------------+----------------------------------------------------+"}')" > /tmp/user-account-list-details.txt
      delegate_to: localhost
      changed_when: false

    - name: Debug output of formatted file contents
      shell: cat /tmp/user-account-list-details.txt
      register: formatted_file_output
      changed_when: false

    - name: Append debug output to file on control node
      lineinfile:
        line: |
          {{ inventory_hostname }} Audit report for user accounts on OCI Linux Compute instances:
          {{ formatted_file_output.stdout }}
        path: /tmp/user-account-list-details.txt
        insertafter: EOF
      delegate_to: localhost
