---
- name: Monitor /var/log/secure for COMMAND=/bin/su -
  hosts: all
  gather_facts: yes
    
  tasks:
    - name: Delete root login attempt details file if it exist    
      file:
        path: /tmp/root-login-attempt-details.txt    
        state: absent
      delegate_to: localhost 

    - name: Read /var/log/secure
      command: sudo cat /var/log/secure
      register: secure_log_output
    - debug:
            var: secure_log_output.stdout_lines

    - name: Filter lines containing COMMAND=/bin/su -
      set_fact:
        filtered_lines: "{{ secure_log_output.stdout_lines | select('search', '^.*COMMAND=/bin/su -(| root)$') | list }}"

    - name: Display each matching line
      block:
        - name: Create a temporary file
          tempfile:
            state: file
            suffix: '.txt'
          register: temp_file    

        - name: Append debug output to file on control node
          lineinfile:
            path: "{{ temp_file.path}}"
            line: "{{ item }}"          
            create: yes  
          with_items: "{{ filtered_lines }}" 

        - name: Display the content of the temporary file
          command: cat "{{ temp_file.path }}"  
          register: temp_file_content
          changed_when: false

        - name: Print each line individually
          debug:
            msg: "{{ item }}"  
          with_items: "{{ temp_file_content.stdout_lines }}"  
          loop_control:
            index_var: index

        - name: Append the content of the temporary file to a local log file
          local_action: shell echo "{{ temp_file_content.stdout }}" >> /tmp/root-login-attempt-details.txt

    - name: Convert line endings from unix to windows format
      shell: sed -i 's/$/\r/' /tmp/root-login-attempt-details.txt
      delegate_to: localhost

    - name: Convert line endings from unix to windows format
      shell: sed -i 's/$/\r/' /tmp/root-login-attempt-details.txt
      delegate_to: localhost
 
    - name: Read file /tmp/root-login-attempt-details.txt content
      slurp:
        path: /tmp/root-login-attempt-details.txt
      delegate_to: localhost
      register: root_login_attempt_file_contents
