---
- name: Check OSMs connectivity
  hosts: your_target_host
  gather_facts: no
  tasks:
    - name: Execute osms test command
      shell: osms test
      register: osms_test_output
      ignore_errors: yes

    - name: Check connectivity status
      set_fact:
        connectivity_status: >
          {% if "There does not appear to be any network or connectivity issues." in osms_test_output.stdout %}
            OK
          {% elif "Unable to connect to server." in osms_test_output.stdout %}
            Issue Detected
          {% else %}
            Unknown
          {% endif %}

    - name: Print connectivity status
      debug:
        msg: "OSMs connectivity status on {{ inventory_hostname }}: {{ connectivity_status }}"

    - name: Group hosts by connectivity status
      group_by:
        key: "{{ 'issue_detected_hosts' if connectivity_status == 'Issue Detected' else 'no_issue_hosts' }}"

- name: Send email if issue detected
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get the list of hosts with connectivity issues
      set_fact:
        issue_hosts: "{{ groups['issue_detected_hosts'] | default([]) }}"

    - name: Send email if issue detected
      when: issue_hosts | length > 0
      mail:
        to: your_email@example.com
        subject: "OSMs Connectivity Issue Detected on {{ issue_hosts }}"
        body: |
          The osms test command detected connectivity issues on the following hosts: {{ issue_hosts | join(', ') }}. Please investigate.
