---
- name: Monitor /var/log/secure for COMMAND=/bin/su -
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read /var/log/secure
      command: cat /var/log/secure
      register: log_output

    - name: Filter lines containing COMMAND=/bin/su -
      set_fact:
        filtered_lines: "{{ log_output.stdout_lines | select('search', 'COMMAND=/bin/su -') | list }}"

    - name: Append matching lines to log file
      copy:
        content: "{{ item }}"
        dest: /path/to/append.log
        remote_src: false
        mode: "0644"
      with_items: "{{ filtered_lines }}"
