---
- name: Collect available package details and patch the servers
  hosts: all
  gather_facts: yes
  become: true
  
  tasks:
    - name: Get the current date
      set_fact: 
        current_date: "{{ ansible_date_time.date }}"

    - name: Create a folder to store Collect available packages files
      file: 
        path: "/dump/OS-Patch-Logs/{{ inventory_hostname }}-{{ current_date }}"
        state: directory
      register: log_dir  
  
    - name: Collect available packages name specific to server
      shell: yum -q check-update | awk '{print $1}' |sed 's/\.x86_64$//' |sed 's/\.noarch$//' |sed 's/\.src$//' > {{ log_dir.path }}/{{ inventory_hostname }}-package-name.txt
      changed_when: false
      no_log: true  
       
    - name: Collect available package versions specific to server
      shell: yum -q check-update | awk '{print $2}' > {{ log_dir.path }}/{{ inventory_hostname }}-package-version.txt
      changed_when: false  
      no_log: true   
       
    - name: Collect package names and package version details in installable format specific to server
      shell: paste -d '-' {{ log_dir.path }}/{{ inventory_hostname }}-package-name.txt {{ log_dir.path }}/{{ inventory_hostname }}-package-version.txt | sed 's/\n/-/' > {{ log_dir.path }}/{{ inventory_hostname }}-only-packages-needs-install.txt
      changed_when: false
      
    - name:  Backup of package files generated to Install Same Package updates across all environments
      shell: |
        cp -rp {{ log_dir.path }}/{{ inventory_hostname }}-package-name.txt {{ log_dir.path }}/{{ inventory_hostname }}-package-name-$(date +"%y-%m-%d-%H-%m-%s").txt
        cp -rp {{ log_dir.path }}/{{ inventory_hostname }}-package-version.txt {{ log_dir.path }}/{{ inventory_hostname }}-package-version-$(date +"%y-%m-%d-%H-%m-%s").txt
        cp -rp {{ log_dir.path }}/{{ inventory_hostname }}-only-packages-needs-install.txt {{ log_dir.path }}/{{ inventory_hostname }}-only-packages-needs-install-$(date +"%y-%m-%d-%H-%m-%s").txt

