---
- name: Run multiple shell commands
  hosts: your_target_host
  become: yes
  
  tasks:
    - name: Task 1
      shell: echo "Hello, World!"

    - name: Task 2
      shell: ls -la /tmp

    - name: Task 3
      shell: whoami
