---
- name: Copy file names with "crash" to a new file
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Find files with "crash" in the name
      find:
        paths: "/path/to/files"  # Replace with the actual path to your files
        patterns: "*crash*"
        recurse: yes
        file_type: any
      register: files_found

    - name: Create a list of file names
      set_fact:
        file_names: "{{ files_found.files | map(attribute='path') | list }}"

    - name: Write file names to a new file
      copy:
        content: "{{ file_names | join('\n') }}"
        dest: "/tmp/new_file.txt"
