---
- name: Change Root Password
  hosts: your_server_group
  become: yes
  tasks:
    - name: Set root password
      user:
        name: root
        password: "{{ new_root_password | password_hash('sha512', 'mysecretsalt') }}"
        update_password: always
