- name: Audit user accounts on Linux VMs
  hosts: linux_vms
  gather_facts: yes

  tasks:
    - name: Get list of all user accounts
      shell: cat /etc/passwd | cut -d ":" -f 1
      register: user_list
      changed_when: false

    - name: Generate user account audit report
      run_once: true
      delegate_to: localhost
      vars:
        columns: "User Account,UID,GID,Home Directory,Shell,Account Expiry,Password Expiry,Last Login"
      shell: |
        echo "{{ columns }}"
        for user in {{ user_list.stdout_lines }}; do
          echo "$user,$(id -u $user),$(id -g $user),$(getent passwd $user | cut -d ':' -f 6),$(getent passwd $user | cut -d ':' -f 7),$(chage -l $user | grep 'Account expires' | cut -d ':' -f 2),$(chage -l $user | grep 'Password expires' | cut -d ':' -f 2),$(last -n 1 -w -F $user | awk '{print $4,$5,$6,$7,$8}')"
        done
      register: report_output
      changed_when: false

    - name: Save report to file
      run_once: true
      delegate_to: localhost
      copy:
        content: "{{ report_output.stdout }}"
        dest: "/tmp/user_audit_report_{{ ansible_date_time.date }}.csv"
