---
- name: Audit user accounts on Linux VMs
  hosts: linux_vms
  gather_facts: yes

  tasks:
    - name: Get list of all user accounts
      shell: cat /etc/passwd | cut -d ":" -f 1
      register: user_list
      changed_when: false

    - name: Generate user account audit report
      shell: |
        for user in {{ user_list.stdout_lines }}; do
          echo "User account: $user"
          echo "UID: $(id -u $user)"
          echo "GID: $(id -g $user)"
          echo "Home directory: $(getent passwd $user | cut -d ':' -f 6)"
          echo "Shell: $(getent passwd $user | cut -d ':' -f 7)"
          echo "Account expiry: $(chage -l $user | grep 'Account expires' | cut -d ':' -f 2)"
          echo "Password expiry: $(chage -l $user | grep 'Password expires' | cut -d ':' -f 2)"
          echo "Last login: $(last -n 1 -w -F $user | awk '{print $4,$5,$6,$7,$8}')"
          echo ""
        done
      register: report_output
      changed_when: false

    - name: Save report to file
      copy:
        content: "{{ report_output.stdout }}"
        dest: "/tmp/user_audit_report_{{ ansible_date_time.date }}.txt"
