- name: Audit user accounts on OCI Linux Compute instances
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get list of all user accounts
      shell: cat /etc/passwd | cut -d ":" -f 1
      register: user_list
      changed_when: false

    - name: Delete user account details file if it exists
      file:
        path: /tmp/user-account-list-details.txt
        state: absent
      delegate_to: localhost

    - name: Create user account details file if it doesn't exist
      file:
        path: /tmp/user-account-list-details.txt
        state: touch
      delegate_to: localhost
      when: not ansible_check_mode

    - name: Generate user account audit report
      shell: |
        printf "%-20s %-30s %-20s %-20s %-20s\n" "Username" "Groups" "Last Login" "Password Expiry" "Last Password Change" > /tmp/user-account-list-details.txt
        for user in {{ user_list.stdout_lines | join(' ') }}; do
          groups=$(groups $user)
          last_login=$(lastlog -u $user |tail -n 1 | cut -c 44-)
          password_expiry=$(chage -l $user | grep 'Password expires' | cut -d ':' -f 2)
          last_password_change=$(chage -l $user | grep 'Last password change' | cut -d ':' -f 2)
          printf "%-20s %-30s %-20s %-20s %-20s\n" "$user" "$groups" "$last_login" "$password_expiry" "$last_password_change" >> /tmp/user-account-list-details.txt
        done
      register: user_audit_report_output
      changed_when: false

    - name: Debug output of audit report
      debug:
        var: user_audit_report_output.stdout_lines

    - name: Write audit report to file
      template:
        src: user-account-list-details.txt.j2
        dest: /tmp/user-account-list-details.txt
      delegate_to: localhost

    - name: Debug output of file
      shell: cat /tmp/user-account-list-details.txt
      register: file_output
      changed_when: false

    - name: Debug output of file contents
      debug:
        var: file_output.stdout



========


{{ inventory_hostname }} Audit report for user accounts on OCI Linux Compute instances:

{% for line in user_audit_report_output.stdout_lines %}
{{ line }}
{% endfor %}

======



- name: Append audit report to file on control node
  lineinfile:
    path: /tmp/user-account-list-details.txt
    line: |
      {{ inventory_hostname }} Audit report for user accounts on OCI Linux Compute instances:

      User account          Groups user is member of          Last login          Password expiry          Last password change
      {% for user in user_list.stdout_lines %}
      {{ "%-20s %-35s %-20s %-25s %s" % (user, groups[user], lastlog[user], chage_password_expiry[user], chage_last_password_change[user]) }}
      {% endfor %}
    insertafter: EOF
  delegate_to: localhost

