- name: Audit user accounts on OCI Linux Compute instances
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get list of all user accounts
      shell: cat /etc/passwd | cut -d ":" -f 1
      register: user_list
      changed_when: false

    - name: Delete user account details file if it exists
      file:
        path: /tmp/user-account-list-details.txt
        state: absent
      delegate_to: localhost

    - name: Create user account details file if it doesn't exist
      file:
        path: /tmp/user-account-list-details.txt
        state: touch
      delegate_to: localhost
      when: not ansible_check_mode

    - name: Generate user account audit report
      template:
        src: user_account_audit_report.j2
        dest: /tmp/user-account-list-details.txt
      delegate_to: localhost



=======


{{ inventory_hostname }} Audit report for user accounts on OCI Linux Compute instances:

| User account | Groups user is member of | Last login | Password expiry | Last password change |
|--------------|-------------------------|------------|-----------------|----------------------|
{% for user in user_list.stdout_lines %}
| {{ user }} | {{ groups[user] }} | {{ command["lastlog -u " ~ user ~ " | tail -n 1 | cut -c 44-"] }} | {{ command["chage -l " ~ user ~ " | grep 'Password expires' | cut -d ':' -f 2"] }} | {{ command["chage -l " ~ user ~ " | grep 'Last password change' | cut -d ':' -f 2"] }} |
{% endfor %}



======
