- name: Audit user accounts on OCI Linux Compute instances
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get list of all user accounts
      shell: cat /etc/passwd | cut -d ":" -f 1
      register: user_list
      changed_when: false

    - name: Generate user account audit report
      template:
        src: user_audit_report.j2
        dest: /tmp/user-account-list-details.txt
      delegate_to: localhost
      vars:
        user_list: "{{ user_list.stdout_lines }}"
        groups: "{{ hostvars[inventory_hostname]['ansible_facts']['ansible_local']['groups'] }}"
        command: "{{ ansible_playbook_python }} -m shell"

    - name: Print user account audit report to console
      command: cat /tmp/user-account-list-details.txt



======


{{ inventory_hostname }} Audit report for user accounts on OCI Linux Compute instances:

| User account | Groups user is member of | Last login | Password expiry | Last password change |
|--------------|-------------------------|------------|-----------------|----------------------|
{% for user in user_list %}
| {{ user }} | {% if groups[user] is defined %}{{ groups[user] }}{% endif %} | {{ `lastlog -u ` ~ user ~ ` | tail -n 1 | cut -c 44-` }} | {{ `chage -l ` ~ user ~ ` | grep 'Password expires' | cut -d ':' -f 2` }} | {{ `chage -l ` ~ user ~ ` | grep 'Last password change' | cut -d ':' -f 2` }} |
{% endfor %}

