---
- name: Audit user accounts on Linux VMs
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get list of all user accounts
      shell: cat /etc/passwd | cut -d ":" -f 1
      register: user_list
      changed_when: false

    - name: Generate user account audit report
      shell: |
        for user in {{ user_list.stdout_lines | join(' ') }}; do
          echo "User account: $user"
          echo "Groups user is member of: $(groups $user)"
          echo "Password expiry: $(chage -l $user | grep 'Password expires' | cut -d ':' -f 2)"
          echo "Last password change: $(chage -l $user | grep 'Last password change' | cut -d ':' -f 2)"
          echo "Last login: $(lastlog -u $user |tail -n 1 | cut -c 44-)"
          echo ""
        done
      register: report_output
      changed_when: false

    - name: Save report to file
      copy:
        content: "{{ report_output.stdout }}"
        dest: "/tmp/user_audit_report_{{ ansible_date_time.date }}.txt"
