---
- name: Collect sudo and sshd configuration details
  hosts: all
  become: yes
  tasks:
    - name: Collect configuration details
      shell: |
        echo "$(grep -vE '^#|^$' /etc/sudoers)
        $(grep -E '^PermitRootLogin' /etc/ssh/sshd_config)
        $(grep -E '^AllowUsers' /etc/ssh/sshd_config)
        $(grep -E '^AllowGroups' /etc/ssh/sshd_config || true)"
      register: config_details

    - name: Append configuration details to file
      copy:
        content: "{{ config_details.stdout }}"
        dest: /path/to/output.txt
        mode: '0644'
